name: "Setup macOS"

inputs:
  runs-on:
    required: true

runs:
  using: "composite"
  steps:
    - name: Optionally install OpenSSL
      if: ${{ inputs.runs-on == 'macos-13' }}
      shell: bash
      run: brew install openssl@3

    - name: Install macOS dependencies
      shell: bash
      run: |
        brew install llvm opencv
        find $(brew --prefix opencv)/lib -name "*.dylib" -type f -delete
        TBB_ROOT=$(brew --prefix tbb)
        RUSTFLAGS="-L $TBB_ROOT/lib $RUSTFLAGS"
        echo "RUSTFLAGS=$RUSTFLAGS" >> $GITHUB_ENV
        echo "TBB_ROOT=$TBB_ROOT" >> $GITHUB_ENV
        echo "PATH=$TBB_ROOT/bin:$PATH" >> $GITHUB_ENV
        if [[ "${{ inputs.runs-on }}" == "macos-13" ]]; then
          brew install openssl@3
          echo 'export OPENSSL_DIR=$(brew --prefix openssl@3)' >> $GITHUB_ENV
         fi
